server:
  port: 8762


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: user_eureka_client_8762 #修改本服务在Eureka中的服务名称
    prefer-ip-address: true     #标注此配置查看此微服务的访问路径时可以显示IP地址

info: #在配置信息中加载关于
  app.name: user_eureka_client_8762
  company.name: www.test.dapengjiaoyu.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"

spring:
  application:
    name: user_eureka_client
