server:
  port: 8762


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: user_eureka_client_8762 #修改本服务在Eureka中的服务名称
    prefer-ip-address: true     #标注此配置查看此微服务的访问路径时可以显示IP地址

info: #在配置信息中加载关于
  app.name: user_eureka_client_8762
  company.name: www.test.dapengjiaoyu.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:
    database: 0
  application:
    name: user-eureka-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot_module?useSSL=true&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: lgq123456

mybatis-plus:
  type-aliases-package: com.system.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/**/*.xml                       # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰uName自动映射到u_name
  global-config:
    refresh-mapper: true

logging:
  level:
    com.system.dao: debug