server:
  port: 8765


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: view_feign_8765 #修改本服务在Eureka中的服务名称
    prefer-ip-address: true     #标注此配置查看此微服务的访问路径时可以显示IP地址

  info: #在配置信息中加载关于
    app.name: view_feign_8765
    company.name: www.test.dapengjiaoyu.com
    build.artifactId: "@project.artifactId@"
    build.version: "@project.version@"


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:
    database: 0
  application:
    name: view-feign
  thymeleaf:
    cache: false  #禁用模板引擎的缓存

#配置使用断路器
feign:
  hystrix:
    enabled: true
